spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: zhangqian
    url: jdbc:mysql://localhost:3306/a?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: 127.0.0.1  # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password:   # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10  # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
    timeout: 1000   # 连接超时时间（毫秒）
  mail:
    host: smtp.163.com
    username: zhangqianfun@163.com
    password: EBLFNNXFSFVARYSW
    default-encoding: UTF-8
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /
    port: 5672
  freemarker:
    cache: false
    suffix: .html
    charset: UTF-8
    template-loader-path: classpath:/templates/
  mvc:
    view:
      suffix: .jsp
      prefix: /
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
server:
  port: 8080